### ISSUE TITLE
Add icon with shared status

### ISSUE THREAD

**Issue by kans** [Floobits/floobits-intellij#113]
With add/delete from workspace, we need an indicator so users are'nt confused.

Unfortunately, we have to step outside of the open api to do this, which would also mean making the base stuff another plugin we specify as a dep, or handling that ourselves like we do with python common.

see: http://devnet.jetbrains.com/message/5256163#5256163 and 
import com.intellij.ide.IconProvider;
import com.intellij.openapi.util.IconLoader;
import com.intellij.psi.PsiElement;
import com.intellij.psi.PsiFile;

**Comment by btipling** [comment]
This is over a year old and the UI has changed a lot and I still do not really understand the issue. I think delete from workspace already works and makes sense as is.
