### ISSUE TITLE
Customizable Cursor Colors

### ISSUE THREAD

**Issue by jaswsinc** [Floobits/floobits-intellij#130]
#### Feature request... customizable cursor colors.

I only bring it up... because it seems that connecting to a Floobits workspace from PhpStorm will choose a random color for each client? Or, am I missing something?

In PhpStorm I can see that each person in chat gets a color, and this coincides with the caret row background color in the editor. However, there's no way to customize this for a team environment; which would make it easier to recognize each other; and to keep it more consistent so that colors don't change from time-to-time.

@raamdev (an associate of mine) mentioned that he sort of expected this to be a configurable option in the `.floorc` file; making it possible to customize the color across editors.

I tend to agree, but I can see where conflicts would arise too.. e.g. multiple team members choose the same color. I suppose shading could be applied. Not sure how that would work exactly, but if two team members choose the same color perhaps that could be detected and one of those is shaded slightly to differentiate from the other.

Anyway, just wanted to bring it up as a possibility. ~ Loving Floobits!

**Comment by BlitZz96** [comment]
Any progress in this issue?

**Comment by btipling** [comment]
We could let people pick a cursor color in django settings and then broadcast it to colab and have it be part of user info. :/

**Comment by enyo** [comment]
Every one in my team got the color red assigned to them. This is very annoying when collaborating. I think that the color should be stored in the user profile as suggested by @btipling .
Ideally there is a way to override it on a project basis.

**Comment by ggreer** [comment]
OK, you can choose your own color by going to https://floobits.com/dash/settings#user

See [this blog post](https://news.floobits.com/2015/11/09/new-feature-custom-highlight-colors/) for a little more on that.
