### ISSUE TITLE
Undo shows confirm dialog "Undo Floobits?"

### ISSUE THREAD

**Issue by rickyk586** [Floobits/floobits-intellij#189]
On Windows.

Not entirely sure what causes this to happen or not after an undo operation (ctrl+z or Edit -> Undo), but it might occur only after another user has updated a file on the same workplace.

![greek_mysql - c__users_ricka_floobits_cdrake_greekrush_greek_mysql - _serve-000243](https://cloud.githubusercontent.com/assets/1494909/5674631/c1c4fe4a-9762-11e4-958c-c28caa9d2882.png)

**Comment by kans** [comment]
This is actually not actually caused by Floobits, but Intellij.  I don't think we can do anything about it.

**Comment by btipling** [comment]
Yes undo is really tricky when collaborating. When you see this dialog it means you just tried to undo someone else's change.

**Comment by rickyk586** [comment]
This happens even if the other person's change was in a different file. Is there any way to get around that?

**Comment by Mnemon1k** [comment]
rickyk586, yes

**Comment by lilith** [comment]
@Mnemon1k  Yes, there is a workaround?
