### ISSUE TITLE
Annoying warning in logs

### ISSUE THREAD

**Issue by ggreer** [Floobits/floobits-intellij#201]
[  56970]   WARN - openapi.wm.impl.ToolWindowImpl - ToolWindow icons should be 13x13. Please fix ToolWindow (ID:  Floobits Chat) or icon jar:file:/home/dfortunov/.PyCharm40/config/plugins/intellij-plugin/lib/intellij-plugin.jar!/icons/floo.png

We should probably resize that icon.

**Comment by btipling** [comment]
This fixed.
