### ISSUE TITLE
Renaming folders not syncing

### ISSUE THREAD

**Issue by geoffreyd** [Floobits/floobits-intellij#208]
When I rename a folder (or sometimes even a file), this change is not reflected remotely. To get this to show, I have to manually add the now renamed folder to the workspace, and get my collaborator to remove the old named folder from the workspace (and then delete it).

**Comment by kans** [comment]
@geoffreyd 
What version of the plugin are you using?

**Comment by geoffreyd** [comment]
1.5.1 but this was also happening on the 1.4.* versions

**Comment by btipling** [comment]
How are you renaming the folder? You need to right click on it, refactor -> rename. Doing it outside of IntelliJ wont work. We don't get events for that I don't think.

**Comment by geoffreyd** [comment]
Yes, the renames where done from inside RubyMine using the refactor. We had to rename a number of folders, so we tested different ways, even having my team member disconnect and reconnect, but the new folder was never there until we manually added it to the workspace.

**Comment by btipling** [comment]
That's pretty strange since when I rename files it works. I wonder if you wouldn't mind sharing your intellij log with us when you tried this. Sorry for the late response. Is there any kind of exception there?

**Comment by btipling** [comment]
This is pretty old and I can't reproduce. Feel free to re-open it if you have additional information.  Thank you for letting us know!
