### ISSUE TITLE
Better support for big repos/workspaces

### ISSUE THREAD

**Issue by ggreer** [Floobits/floobits-intellij#212]
Right now, we have a 100MB-ish limit on workspaces. With a few tweaks, we could drastically improve this. Many of these changes need to be made on the back-end, but we'll also need to increase the limit in our plugins once we've done this. Putting this issue in intellij because that's typically the editor people use with massive java enterprise projects.

**Comment by ggreer** [comment]
Example repo that totally borks: https://svn.kuali.org/repos/ole/trunk/

**Comment by peris** [comment]
Is there a process to vote on issues? I would love to see this fixed soon so that I can try it for our team.

**Comment by btipling** [comment]
I think sparse mode fixes this. It will be released soon.

**Comment by btipling** [comment]
@peris can you try the new option when sharing to only upload the directory you want to work on and see if that works for you please?

**Comment by btipling** [comment]
Sparse mode should fix this.
