### ISSUE TITLE
"In Browser" operations not working on Ubuntu

### ISSUE THREAD

**Issue by islemaster** [Floobits/floobits-intellij#239]
In my current setup, none of the "open in browser" operations for Floobits are working from RubyMine.

For example, when I click **Tools > Floobits > Open Workspace in Browser** or **Open Settings in Browser** the following exception appears in my event log:

```
UnsupportedOperationException: Desktop API is not supported on the current platform
```

And when using **Tools > Floobits > Log In to Website** I get:

```
Floobits: Can't use a browser on this system.
```

A similar error occurs on initial setup if you click "I already have an account."

I assume this means the feature simply isn't implemented yet, but I can't find a development roadmap and it's not listed in issues, so I'm adding it here :grin:.  Note that [IntelliJ plugin help page](https://floobits.com/help/plugins/intellij) doesn't call this out as a current limitation on some platforms, which makes the "I already have an account" flow feel pretty broken for a new-user-experience.  I eventually figured out how to copy my `.floorc.json` from the settings page on the website to integrate my online account with my RubyMine account manually.

Environment:
* Ubuntu 15.04, 64-bit
* RubyMine 7.1.4
* Floobits plugin 1.5.8
* Both Firefox and Chrome are installed

This tool is awesome guys, keep up the good work!

**Comment by ggreer** [comment]
Thanks for the detailed bug report. I didn't know this was an issue on Ubuntu.

I'm on vacation right now, so I don't have a linux machine to test on. We'll figure out a fix or workaround though.

**Comment by btipling** [comment]
Ok we'll fix so it shows the link it wants to go to to let you click on it. Sorry.

**Comment by islemaster** [comment]
Making the link visible as a workaround sounds good.  The only critical issue was setup, and the plugin is  totally usable after manually copying the `.floorc` from my settings page on the website to my local machine.

**Comment by btipling** [comment]
Thanks @islemaster, I've just updated the plugin, can you please update to 1.5.9 and try and open the workspace in the browser (Tools -> Floobits -> Open Workspace in Browser) and tell me how well that works for you? I can't actually reproduce the bug easily. This is kind of a blind work around.

**Comment by btipling** [comment]
I'm going to close this issue now. Please let me know if you think we should work on it some more.

**Comment by islemaster** [comment]
I've updated to 1.5.9.  The new message when I hit **Tools > Floobits > Open Workspace in Browser** or **Open Settings in Browser** is

```
*error*: Could not open your system's browser.
```

This is followed by a *status* message with a link to the URL I was attempting to reach.  Clicking that URL results in `NullPointerException: null` in RubyMine's Event Log.

**Tools > Floobits > Log In to Website** is grayed out; I suspect because I went ahead and copied `.floorc` from the website so no log-in step is needed, not because of anything related to this bug.

I did a little digging, and [according to this thread](https://devnet.jetbrains.com/message/4971065#4971065) the usual way for a plugin to open a browser window is to use the `launchBrowser` method on [`com.intellij.ide.BrowserUtil`](https://github.com/JetBrains/intellij-community/blob/master/platform/platform-api/src/com/intellij/ide/BrowserUtil.java); however `launchBrowser` is deprecated and recommends using `BrowserUtil.browse(url)` now.  It might be worth trying that from within your [Utils.openInBrowser](https://github.com/Floobits/floobits-intellij/blob/dea37b1e6bd90aa8d775e5c9a9d4915e76711c51/src/floobits/common/Utils.java#L290) method.

I'm not set up for plugin development at the moment, but if you guys prefer I'd be happy to try and fix this myself and submit a PR.  Seems practical since I've got an environment that repro's the issue.

**Comment by btipling** [comment]
Wow thanks! I'll take your changes and work with them. I had considered searching for how IntelliJ was doing this, but I hadn't had time yet. This is great. I am going to make a couple of changes. I'd put those changes in our Utils function instead of replacing the Utils function everywhere, that way there's only a single place to change how we open URLs.
