### ISSUE TITLE
Latest update 1.5.11 freezes Android Studio 1.4 x64 in Linux

### ISSUE THREAD

**Issue by azariah001** [Floobits/floobits-intellij#244]
On connection to project workspace in Android Studio 1.4 x64 on Linux, it locks up instantly before the menu has a chance to even close. Manual download and roll back to 1.5.10 fixes the issue.

**Comment by kans** [comment]
@azariah001 

Are there any exceptions in your logs?

**Comment by azariah001** [comment]
Woops I forgot about this. :grimacing: Is probably fixed now but I just found the issue. :stuck_out_tongue: 

In the `src/floobits/dialogs/ShareProjectDialog.java` file line 39 before patch and 43 after is still referring to the `workspaceName` variable which was refactored to `projectName`. Woops. I'm guessing whoever made that particular edit didn't use JetBrain's refactor tool. :stuck_out_tongue:

I'll put a reminder in my calendar to take a look at it tomorrow make sure it has been fixed now. :smile:

**Comment by azariah001** [comment]
Whatever happened at the time is no longer an issue in the most recent version, so.... I'm just gonna close this. Also took a look at that variable and they had just implemented a bunch of illegal character handling which should have made it more stable soooo eh. Weird. No longer an in issue in the latest versions of the plugin sooo yeah. No point hanging around here. :P
