### ISSUE TITLE
Please add a toggle for highlights, it is absolutely abysmal working with them on.

### ISSUE THREAD

**Issue by Buuburn** [Floobits/floobits-intellij#258]
title.

**Comment by ggreer** [comment]
OK, we discussed this and I can reproduce the issue. The immediate fix is to make highlights not so bold and not take up the entire width of the screen. Also, it'd be nice to make the username/icon stick around for a little longer.

**Comment by ApexTier** [comment]
+1 lime green highlights really hurt my eyes and makes it hard to read code especially when using a dark theme.

**Comment by kossmoboleat** [comment]
Is the "immediate fix" a workaround for users or a change in the plugin?
